baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

# theme = 'hugo-theme-stack'
theme = 'PaperMod'

[menu]
[[menu.main]]
  identifier = "post"
  url = "/post/"
  title = ""
  weight = 1
